# Autogenerated wrapper script for aff3ct_jll for x86_64-apple-darwin-march+avx
export libaff3ct, libaff3ct_jl

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("aff3ct")
JLLWrappers.@declare_library_product(libaff3ct, "@rpath/libaff3ct-4.2.0.dylib")
JLLWrappers.@declare_library_product(libaff3ct_jl, "@rpath/libaff3ct_jl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libaff3ct,
        "lib/libaff3ct-4.2.0.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libaff3ct_jl,
        "lib/libaff3ct_jl.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
