# Autogenerated wrapper script for aff3ct_jll for x86_64-unknown-freebsd-march+avx2
export libaff3ct, libaff3ct_jl

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("aff3ct")
JLLWrappers.@declare_library_product(libaff3ct, "libaff3ct-4.2.0.so")
JLLWrappers.@declare_library_product(libaff3ct_jl, "libaff3ct_jl.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libaff3ct,
        "lib/libaff3ct-4.2.0.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libaff3ct_jl,
        "lib/libaff3ct_jl.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
